### ISSUE TITLE
4.0.0 issue  Runtime.ImportModuleError: Unable to import module 

### ISSUE THREAD

**Issue by himalacharya** [pyca/bcrypt#420]
`[ERROR] Runtime.ImportModuleError: Unable to import module 'main': /lib64/libc.so.6: version GLIBC_2.28' not found (required by /var/task/bcrypt/_bcrypt.abi3.so)`

I have used Github action to run a workflow with required packages in requirements.txt

```
bcrypt
cryptography
```
But the above issue is raised while executing the code after above packages are installed. But the issue is solved by downgrading bcrypt to 3.2.2 and cryptography to 3.4.8. 

In documentation , it is mentioned to use updated pip version and since github action works to fetch new version. 

How to solve this issue to upgrade bcrypt package?

**Comment by alex** [comment]
You're going to need to give us a lot more information for us to help
here. How are you building this, and how are you running this? Are you
by chance using AWS lambda?

On Mon, Sep 19, 2022 at 10:43 PM Himal ***@***.***> wrote:
>
> [ERROR] Runtime.ImportModuleError: Unable to import module 'main': /lib64/libc.so.6: version GLIBC_2.28' not found (required by /var/task/bcrypt/_bcrypt.abi3.so)
>
> I have used Github action to run a workflow with required packages in requirements.txt
>
> bcrypt
> cryptography
>
> But the above issue is raised while executing the code after above packages are installed. But the issue is solved by downgrading bcrypt to 3.2.2 and cryptography to 3.4.8.
>
> In documentation , it is mentioned to use updated pip version and since github action works to fetch new version.
>
> How to solve this issue to upgrade bcrypt package?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by himalacharya** [comment]
I am using AWS lambda and codes are pushed to AWS lambda by using Github action flow. 
```

name: Project name
on:
  # Trigger the workflow on push
  push:
    branches: 
      # Push events on main branch
      - main

# The Job defines a series of steps that execute on the same runner.
jobs:

  CI:
    # Define the runner used in the workflow
    runs-on: ubuntu-latest
    steps:   
      # Check out repo so our workflow can access it
      - uses: actions/checkout@v2
      
      # Step-1 Setup Python
      - name: Set up Python
        # This action sets up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          # optional: architecture: x64 x64 or x86. Defaults to x64 if not specified

      # Step-2 Install Python Virtual ENV
      - name: Install Python Virtual ENV
        run: python3 -m venv env

      # Step-3 Setup Virtual ENV
      # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name:  Virtual ENV
        uses: actions/cache@v2
        id: cache-venv # name for referring later
        with:
          path: venv # what we cache: the Virtual ENV
          # The cache key depends on requirements.txt
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      # Step-4 Build a Virtual ENV, but only if it doesn't already exist
      - name: Activate Virtual ENV
        run: python3 -m venv venv && source ./venv/bin/activate && pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Create archive of dependencies
        run: |
          cd ./venv/lib/python3.8/site-packages
          zip -r9 ../../../../api.zip .
      - name: Add API files to Zip file
        # run: zip -g api.zip -r .env && cd ./app && zip -g ../api.zip -r .
        #Adding env files 
        # run: zip -g api.zip -r .env && zip -g api.zip -r app 
        #Removing env file 
        # run: zip -g api.zip -r app 
        #Adding main.py and config.py
        run: zip -g api.zip -r main.py && zip -g api.zip -r app && zip -g api.zip -r config.py
        
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Download Lambda api.zip
        uses: actions/download-artifact@v2
        with:
          name: api
      - name: Upload to S3
        run: aws s3 cp api.zip s3://project-name/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name project_name --s3-bucket project-name --s3-key api.zip
        env:
          #root user
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

```
 After reaching AWS lambda via API gateway throws an error Internal server error and looking trace found the module import issue in Cloudwatch
